apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: mypassword123   # stringData auto base64-encodes for you
  POSTGRES_USER: myuser
  POSTGRES_DB: myappdb